// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzZzTNHpse0oylDVgLL2-urDnAdhOnxyE',
    appId: '1:339200261872:web:c8cb7b0dc34e694c0b8c35',
    messagingSenderId: '339200261872',
    projectId: 'hackathon-86efa',
    authDomain: 'hackathon-86efa.firebaseapp.com',
    storageBucket: 'hackathon-86efa.appspot.com',
    measurementId: 'G-228MP633SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIbLUOD6O3eFf1DaqCafScQAhiqFAWgNc',
    appId: '1:339200261872:android:e15cc90ec7d335ed0b8c35',
    messagingSenderId: '339200261872',
    projectId: 'hackathon-86efa',
    storageBucket: 'hackathon-86efa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHJZ-Dw8SjWWvqd6zhEST5vBsoIgKmxk',
    appId: '1:339200261872:ios:f9c9b0cdd9d40ded0b8c35',
    messagingSenderId: '339200261872',
    projectId: 'hackathon-86efa',
    storageBucket: 'hackathon-86efa.appspot.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApHJZ-Dw8SjWWvqd6zhEST5vBsoIgKmxk',
    appId: '1:339200261872:ios:f9c9b0cdd9d40ded0b8c35',
    messagingSenderId: '339200261872',
    projectId: 'hackathon-86efa',
    storageBucket: 'hackathon-86efa.appspot.com',
    iosBundleId: 'com.example.tracker',
  );
}
